name: 'Setup Python and uv'
description: 'Sets up Python, uv, and installs dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash
    - name: Install dependencies
      run: |
        uv venv
        uv pip sync requirements.txt
      shell: bash
