name: Upload BlocketAPI to PyPI upon release.

on:
  release:
    types: [created]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv pip install twine
          uv dist build
          twine upload dist/* -u __token__ -p $PYPI_TOKEN
